### ISSUE TITLE
Replay TMC Quotidien Impossible

### ISSUE THREAD

**Issue by amacraigne** [spmjc/plugin.video.freplay#101]
Depuis quelques jours je n'arrive plus à regarder le replay de l'emission quotidien.
Le chargement de la liste des vidéos lève une erreur.
En regardant les logs de kodi, on voit que l'erreur provient de 
```shell
addons/plugin.video.freplay/resources/lib/channels/tf13.py", line 81, in list_videos
                                                videoType = videoType.getText().encode('utf-8').lower()
```

Il semblerait qu'il n'y ai plus la balise strong qui permettait de trouver le type de video (playlist, replay, video)

En supprimant les lignes 
```python
videoType = li.find('strong')
videoType = videoType.getText().encode('utf-8').lower()
```

et 
```python
         if 'playlist' not in videoType:
             if 'replay' in videoType or \
                'video' in videoType or \
                globalvar.ADDON.getSetting(channel + 'Bonus') == 'true':
```

cela semble refonctionner.

Ne compronant pas exactement l'impact de cette modification sur d'autres replay je préfère faire un ticket qu'ouvrir un pull request.

**Comment by spmjc** [comment]
Ca fonctionne chez moi
