### ISSUE TITLE
TF1 - DRM

### ISSUE THREAD

**Issue by Bubus44** [spmjc/plugin.video.freplay#104]
Bonjour,

Les video de série (US) ne se lance pas sur TF1.
TF1 à rajouté un DRM dans le fichier m3u
exemple de ligne ajouté:
## Created with Unified Streaming Platform(version=1.7.25)
#EXT-X-SESSION-KEY:METHOD=SAMPLE-AES,URI="skd://drm-fair.tf1.fr/acquire?id=13443464",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"

Y a t-il un moyen de lire ces videos?

Merci

**Comment by spmjc** [comment]
Non, Desole
