### ISSUE TITLE
Problème avec urllib2

### ISSUE THREAD

**Issue by slundi** [spmjc/plugin.video.freplay#106]
Bonjour,

Sur mon Kodi 8.0.4 (Krypton), j'ai cette erreur :
`19:06:18.176 T:1945758240   DEBUG: ------ Window Deinit (DialogVideoInfo.xml) ------
19:06:18.216 T:1945758240   DEBUG: StartScript - calling plugin FReplay('plugin://plugin.video.freplay/','5','?param=161311124&mode=play&channel$
19:06:18.216 T:1429205920   DEBUG: Thread LanguageInvoker start, auto delete: false
19:06:18.217 T:1429205920    INFO: initializing python engine.
19:06:18.217 T:1429205920   DEBUG: CPythonInvoker(8, /storage/.kodi/addons/plugin.video.freplay/default.py): start processing
19:06:18.237 T:1340859296   DEBUG: Thread scriptobs start, auto delete: false
19:06:18.255 T:1945744288   DEBUG: CAnnouncementManager - Announcement: OnAdd from xbmc
19:06:18.255 T:1945744288   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnAdd
19:06:18.287 T:1679254432   DEBUG: -- Simkl: onNotification
19:06:18.288 T:1679254432   DEBUG: -- Simkl: sender False
19:06:18.317 T:1429205920   DEBUG: -->Python Interpreter Initialized<--
19:06:18.318 T:1429205920   DEBUG: CPythonInvoker(8, /storage/.kodi/addons/plugin.video.freplay/default.py): the source file to load is "/storag$
19:06:18.321 T:1429205920   DEBUG: CPythonInvoker(8, /storage/.kodi/addons/plugin.video.freplay/default.py): setting the Python path to /storage$
19:06:18.322 T:1429205920   DEBUG: CPythonInvoker(8, /storage/.kodi/addons/plugin.video.freplay/default.py): entering source directory /storage/$
19:06:18.322 T:1429205920   DEBUG: CPythonInvoker(8, /storage/.kodi/addons/plugin.video.freplay/default.py): instantiating addon using automatic$
19:06:18.437 T:1945758240   DEBUG: ------ Window Init (DialogBusy.xml) ------
19:06:18.601 T:1913648032   ERROR: CAESinkALSA - snd_pcm_writei(-32) Broken pipe - trying to recover
19:06:19.319 T:1429205920   ERROR: Previous line repeats 1 times.
19:06:19.319 T:1429205920   DEBUG: OS=linux2
19:06:19.319 T:1429205920   DEBUG: Build=17.3 Git:17.3-Krypton
19:06:19.319 T:1429205920   DEBUG: InternetSystem.InternetState
19:06:19.320 T:1429205920   DEBUG: Addon=FReplay 0.6.8
19:06:19.320 T:1429205920   DEBUG: Addon Path=/storage/.kodi/addons/plugin.video.freplay
19:06:19.320 T:1429205920   DEBUG: {'name': ['Le monde secret de la petite brique Lego'], 'mode': ['play'], 'param': ['161311124'], 'channel': [$
19:06:19.398 T:1429205920   DEBUG: CommonFunctions-2.5.1
19:06:19.697 T:1429205920   DEBUG: Log
19:06:19.697 T:1429205920   DEBUG: c=france4&p=161311124
19:06:19.746 T:1429205920   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno -2] Name or service not known>
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.freplay/default.py", line 155, in <module>
                                                log.logGA(channel, param, programName)
                                              File "/storage/.kodi/addons/plugin.video.freplay/resources/lib/log.py", line 63, in logGA
                                                response = urllib2.urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                            URLError: <urlopen error [Errno -2] Name or service not known>
                                            -->End of Python script error report<--
19:06:19.792 T:1945758240   DEBUG: ------ Window Init (DialogNotification.xml) ------
19:06:20.036 T:1429205920    INFO: Python script stopped
19:06:20.037 T:1429205920   DEBUG: Thread LanguageInvoker 1429205920 terminating
19:06:20.037 T:1340859296   DEBUG: Thread scriptobs 1340859296 terminating
19:06:20.074 T:1945758240   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.freplay/?param=161311124&mode=play&$
19:06:20.074 T:1945758240   DEBUG: Playlist Player: no more playable items... aborting playback
19:06:20.075 T:1588200352   DEBUG: Thread BackgroundLoader start, auto delete: false
19:06:20.075 T:1945758240   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x0000, modifier: 0x0
19:06:20.107 T:1588200352   DEBUG: Thread BackgroundLoader 1588200352 terminating
19:06:20.124 T:1945758240   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x0000, modifier: 0x0
19:06:20.361 T:1945758240   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
`

**Comment by slundi** [comment]
J'ai la même erreur sur un Kodi Krypton 17.3 sur Windows 7.

En revanche sur mon Ubuntu, ça marche :/

**Comment by spmjc** [comment]
Ca a l'air d'etre lie a Google Analytics. Est ce que vous avez bloque ce site?
Je ferai une gestiuon d'erreur pour cette situation
