### ISSUE TITLE
Probleme avec M6

### ISSUE THREAD

**Issue by SEB-Appstore** [spmjc/plugin.video.freplay#111]
Depuis 2 jours, les émissions, séries et autres n'apparaissent plus dans les différents répertoires de M6. Tout fonctionnait très bien jusqu’à ce que le flux stoppe et depuis plus rien.... Je me connecte depuis l’étranger pour information.

**Comment by spmjc** [comment]
Ok. Je vais regarder ça

**Comment by SEB-Appstore** [comment]
Ok, merci j’apprécie.
Si t as un API public, ou avec un peu de doc, je pourrais également investiguer.

**Comment by spmjc** [comment]
tout est dans le code: /resources/lib/channels/6play.py
Si tu te sens d'essayer, avec plaisir :)

**Comment by Foncekar** [comment]
En France même soucis, si je trouve un peu de temps je vais aussi essayer de me pencher dessus.

**Comment by spmjc** [comment]
Quelqu'un sur le forum a trouvé une solution

**Comment by Electrocut** [comment]
Bonjour,

Je viens d'appliquer la modification citée sur le forum : https://forum.mpdb.tv/index.php/topic,25341.msg273265.html#msg273265

Je confirme, cela refonctionne !

Encore merci pour cette extension :)

**Comment by jairbubbles** [comment]
En effet ça refonctionne ! Merci grave à vous ma mère va pouvoir regarder "Le meilleur patissier" :wink:

**Comment by tug912** [comment]
Merci. Ca remarche. En revanche l'installation doit se faire manuellement en téléchargeant le zip. Allez vous ajouter le correctif/ la nouvelle version à un repo ? (JUL1EN094 ou un autre ou Superrepo)

Merci par avance.

**Comment by tug912** [comment]
Fonctionnait bien jusqu'à aujourd'hui. Maintenant lorsqu'on tente de lire un contenu : Erreur "contenu protégé par DRM" 

Merci par avance.

**Comment by Electrocut** [comment]
Quelle vidéo as-tu essayé de lire, tug912 ?

Je viens de tester la lecture d'une vidéo prise au hasard (Le meilleur pâtissier saison 6), et la vidéo démarre bien.

**Comment by tug912** [comment]
Certains épisodes de chasseurs d'appart (dernier épisode du jour à paris), ou le dernier Zone interdite sur Disney.... "Vidéo protégée par DRM". Il y en a peu effectivement mais certains affichent le message :/

**Comment by spmjc** [comment]
Rien que l'on puisse faire si on veut rester dans la legalite.
Si M6 decide de proteger ses videos, c'est comme ca. Essaye sur d'autres addons ou captvty. Si le resultat est different, je regarderai, sinon ca restera comme ca.
Dsl.
