### ISSUE TITLE
Incrémenter le numéro de version à 0.6.11

### ISSUE THREAD

**Issue by Flavien** [spmjc/plugin.video.freplay#116]
Des problèmes ont été resolus depuis 0.6.10, en particulier [un problème avec M6](https://github.com/spmjc/plugin.video.freplay/issues/111). Il serait bien d'incrémenter le numéro de version de l'add-on pour que les repos comme JUL1EN094 puissent offrir la nouvelle version.

[J'ai soumi une PR](https://github.com/spmjc/plugin.video.freplay/pull/117).

**Comment by tchirou** [comment]
Hello
Pourrais-tu stp me confirmer que le lien pour télécharger le zip du repo a installer sur kodi pour que le plugin s’auto update est https://github.com/JUL1EN094/JUL1EN094-xbmc-addons ?
Merci beaucoup
