### ISSUE TITLE
Numéro de version et bugs

### ISSUE THREAD

**Issue by Mazus** [spmjc/plugin.video.freplay#132]
Bonjour,

Je suis sur la version 0.6.5 d'après superRepo, alors que je vois ici que la dernière version est 0.6.15.
Est-ce bien la version la plus à jour qui est maintenue sur ce git ?
Sinon j'ai pas mal de video qui ne marchent plus genre TMC ou TF1 avec une erreur du style:

> 
> 13:23:09.619 T:8748   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.AttributeError'>
>                                             Error Contents: 'NoneType' object has no attribute 'getText'
>                                             Traceback (most recent call last):
>                                               File "C:\Users\Piwi\AppData\Roaming\Kodi\addons\plugin.video.freplay-0.6.5\default.py", line 92, in <module>
>                                                 buildShowsList(globalvar.channels[channel][1].list_videos(channel,param))
>                                               File "C:\Users\Piwi\AppData\Roaming\Kodi\addons\plugin.video.freplay-0.6.5\resources\lib\channels\tf13.py", line 78, in list_videos
>                                                 videoType = videoType.getText().encode('utf-8').lower()
>                                             AttributeError: 'NoneType' object has no attribute 'getText'
>                                             -->End of Python script error report<--
> 13:23:09.677 T:8128   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.freplay/?channel=tmc&mode=shows&name=Quotidien%20avec%20Yann%20Barth%c3%a8s&param=%2ftmc%2fquotidien-avec-yann-barthes
> 13:23:09.679 T:8128   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.freplay/?channel=tmc&mode=shows&name=Quotidien%20avec%20Yann%20Barth%c3%a8s&param=%2ftmc%2fquotidien-avec-yann-barthes) failed

Je suis sur laderniere version stable de Kodi (17.6)
Pouvez-vous m'aider ?

Merci.

**Comment by spmjc** [comment]
Installe le reportage de julien094 et ça devrait se résoudre tout seul.
https://forum.mpdb.tv/index.php?action=dlattach;topic=25341.0;attach=16844

**Comment by Mazus** [comment]
Ok, j'avais fini par faire un git clone de ton plugin, mais si le plugin est mis à jour sur le repo de Julien094, c'est encore mieux. Et effectivement tout fonctionne ;) Merci
