### ISSUE TITLE
M6 - Erreurs DRM

### ISSUE THREAD

**Issue by BenPicard** [spmjc/plugin.video.freplay#138]
Bonjour,

Depuis 1 semaine je n'arrive plus à lire les émissions dans M6.

Problème de DRM.

Merci,
Benjamin

**Comment by Electrocut** [comment]
Bonjour,

Doublon du ticket https://github.com/spmjc/plugin.video.freplay/issues/118
Désormais corrigé dans la version 0.6.16

**Comment by BenPicard** [comment]
Désolé du doublon. Merci pour le correctif.

**Comment by Electrocut** [comment]
Merci :)
