### ISSUE TITLE
Problème avec TMC ?

### ISSUE THREAD

**Issue by gordielachance** [spmjc/plugin.video.freplay#140]
Hello; les nouveaux sujets de l'émission quotidien (TMC) ne s'affichent plus avec l'extension, est-ce qu'il y a un bug ?
Merci !

**Comment by quatsch** [comment]
Il faut corriger la ligne suivante dans resources/lib/channels/tf12.py:
urlCatalog='http://api.mytf1.tf1.fr/mobile/2/init?device=ios-tablet'
(rajout du /2)
à priori, si j'ai bien soumis la sorrection ce sera intégré dans la 0.6.16

**Comment by gordielachance** [comment]
ça marche, merci !
