### ISSUE TITLE
Gulli

### ISSUE THREAD

**Issue by spmjc** [spmjc/plugin.video.freplay#15]
Menu

Gulli
    Category
        Show
            Episode
                Video

Key is generated daily. Most likely based on date of day
20150430=dcec6dc639962e15ba91c79fc3ad34b
20150401=f31acf10955404e71a6a6b60652adfbb
1-Category
http://sslreplay.gulli.fr/replay/api?call=%7B%22api_key%22%3A%22andphone_adba197f5708267b4284636b6cee8b8d%22%2C%22method%22%3A%22programme.getFiltersList%22%2C%22params%22%3A%22%22%7D
call={"api_key":"andphone_adba197f5708267b4284636b6cee8b8d","method":"programme.getFiltersList","params":""}

2-Category Detail
http://sslreplay.gulli.fr/replay/api?call=%7B%22api_key%22%3A%22andphone_adba197f5708267b4284636b6cee8b8d%22%2C%22method%22%3A%22programme.getLatestEpisodes%22%2C%22params%22%3A%7B%22category_id%22%3A%22dessins-animes%22%2C%22episode_image_thumb%22%3A%5B380%2C285%5D%2C+%22episode_image_thumb_fiche%22%3A%5B0%2C0%5D%2C+%22program_image_thumb%22%3A%5B720%2C540%5D%2C+%22episode_image_fiche%22%3A%5B1440%2C1080%5D%7D%7D
Call={"api_key":"andphone_adba197f5708267b4284636b6cee8b8d","method":"programme.getLatestEpisodes","params":{"category_id":"dessins-animes","episode_image_thumb":[380,285], "episode_image_thumb_fiche":[0,0], "program_image_thumb":[720,540], "episode_image_fiche":[1440,1080]}}

3-Show Detail (actually category details)
http://sslreplay.gulli.fr/replay/api?call=%7B%22api_key%22%3A%22andphone_adba197f5708267b4284636b6cee8b8d%22%2C%22method%22%3A%22programme.getEpisodesByCategoryId%22%2C%22params%22%3A%7B%22category_id%22%3A%22dessins-animes%22%2C%22episode_image_thumb%22%3A%5B380%2C285%5D%2C+%22episode_image_thumb_fiche%22%3A%5B0%2C0%5D%2C+%22program_image_thumb%22%3A%5B720%2C540%5D%2C+%22episode_image_fiche%22%3A%5B1440%2C1080%5D%7D%7D
Call={"api_key":"andphone_adba197f5708267b4284636b6cee8b8d","method":"programme.getEpisodesByCategoryId","params":{"category_id":"dessins-animes","episode_image_thumb":[380,285], "episode_image_thumb_fiche":[0,0], "program_image_thumb":[720,540], "episode_image_fiche":[1440,1080]}}

**Comment by TmpName** [comment]
There is already a working Guili replay from JUL1EN094, you can take a look on the code.
