### ISSUE TITLE
TV5 Monde

### ISSUE THREAD

**Issue by spmjc** [spmjc/plugin.video.freplay#26]
Categories:

http://www.tv5mondeplus.com/get/videos?sort=28&type=genre&pg=0 (setting for # of pages to retrieve)
Titre + Image + Description?
class=\"image-tv\"\u003e\n\t\t\u003ca title=\"Le melon de Cavaillon\" href=\"\/video\/25-06-2013\/le-melon-de-cavaillon-488616\"\u003e \u003cimg src=\"http:\/\/media3.tv5mondeplus.com\/sites\/tv5mondeplus.com\/files\/imagecache\/grille170x96\/vodimg\/10059729183713898.jpg\" alt=\"\" title=\"\"  class=\"imagecache imagecache-grille170x96\" width=\"170\" height=\"96\" \/\u003e \u003c\/a\u003e\n\t\t\u003c\/div\u003e\n\t\t\u003cdiv class=\"description\"\u003e\n\t\t\t\u003ch4 class=\"amasis-bol\"\u003e\u003ca href=\"\/video\/25-06-2013\/le-melon-de-cavaillon-488616\"\u003e\u00c9PICERIE FINE: Le melon de Cavaillon\u003c\/a\u003e\u003c\/h4\u003e\n\t\t\t\u003cp class=\"date\"\u003e\n\t\t\tmar, 25 juin. 2013, 00h GMT\t\t        \u003c\/p\u003e\n\t\t\t\t\t\t\u003cp class=\"icon\"\u003e\u003cimg alt=\"logo\" src=\"\/sites\/tv5mondeplus.com\/files\/tv5mond.png\"\u003e\u003c\/p\u003e\n\t\t\u003c\/div\u003e\n\t\t\n\t\t\t\t\n\t\u003c\/div\u003e\n\t\u003cdiv class=\"item-hover hide\"\u003e\n\t\t\u003ch4 class=\"amasis-bol\"\u003e\u003ca href=\"\/video\/25-06-2013\/le-melon-de-cavaillon-488616\"\u003e\u00c9PICERIE FINE: Le melon de Cavaillon\u003c\/a\u003e\u003c\/h4\u003e\t    \t    \n\t        \u003cp\u003e\u003ca href=\"\/video\/25-06-2013\/le-melon-de-cavaillon-488616\" \u003eLe melon de Cavaillon\n\nAu coeur de la Provence, nich\u00e9e au pied des... 

video links
http://www.tv5mondeplus.com/video-xml/get/829681

**Comment by sy6sy2** [comment]
Done
