### ISSUE TITLE
Potential Channels

### ISSUE THREAD

**Issue by spmjc** [spmjc/plugin.video.freplay#28]
Equipe21
Numero 23
RMC Decouverte
Allocine
RTBF
Euronews
INA
http://www.ztele.com/webtele
http://www.musiqueplus.com/videos
https://www.canal-u.tv/
http://zonevideo.telequebec.tv/ (iPad)

**Comment by gdusart** [comment]
Pour RTBF: http://www.rtbf.be/auvio/ semble assez facile à traiter, je peux me mettre dessus.
