### ISSUE TITLE
https://cnes.fr/

### ISSUE THREAD

**Issue by spmjc** [spmjc/plugin.video.freplay#46]

**Comment by orion2036** [comment]
http://videotheque.cnes.fr/index.php

**Comment by sy6sy2** [comment]
En cours

**Comment by orion2036** [comment]
Merci :)

**Comment by sy6sy2** [comment]
Je viens de pusher l'ajout de CNES Orion2036. Si tu veux essayer ;-)
Si tu trouves des bugs et/ou améliorations possible n'hésite pas !

Sylvain

**Comment by orion2036** [comment]
Je ne suis pas codeur mais j'apprecie ces add-ons vidéos qui permettent d'acceder simplement a des videos. Merci pour ta contribution Sylvain.
