### ISSUE TITLE
Canal U

### ISSUE THREAD

**Issue by orion2036** [spmjc/plugin.video.freplay#47]
Les caractères typiquement français tels que ' ou é n'apparaissent pas dans le menu de sélection des thèmes, par exemple "sciences de lingnieur" au lieu de "sciences de l'ingénieur"
Il n'est pas possible de changer de page une fois dans le thème sélectionné, seules 10 vidéos sont disponibles à la lecture.
Le volet de description des vidéos contient des caractères  XML. La date de diffusion est bloquée sur 31/12/1969.
Les vidéos se lançent sans problèmes.
C'est un bon début, merci d'avoir ajouté cette chaîne :)

---

Typical french character like ' or é does not appear in the theme selection menu, for example "sciences de lingnieur" instead of "sciences de l'ingénieur"
It is not possible to change the page once into the selected theme, only 10 videos are available.
The videos description part contains XML characters. The broadcast date is stuck on 31/12/1969.

**Comment by JUL1EN094** [comment]
J'essaie de prendre en charge tt ca. Les pb d'encodage ca me connait un peu

**Comment by JUL1EN094** [comment]
Première tentative : https://github.com/spmjc/plugin.video.freplay/commit/b544e2aaed8282bca025198399d50aea553348e0

Devrait résoudre les pb d'encodage. Merci de tester et faire un retour.

Reste le pb des 10 videos

**Comment by spmjc** [comment]
Pour les 10 videos, j'ai pris le flux RSS. Peut etre que ce flux n'affiche pas toutes les videos..

**Comment by orion2036** [comment]
Je suis impressionné par autant de réactivité de votre part, merci beaucoup :) J'aimerais tester la correction du bug d'encodage mais je suppose qu'il faut compiler et j'avoue que je ne sais pas comment faire. Je vais me renseigner sur Google.

**Comment by JUL1EN094** [comment]
+1 spmjc, j'ai remarqué ca. Le flux rss ne retourne que 10 liens max... Je vais jeter un oeil je pense qu'il y a moyen.

orion2036, pour tester, tu as juste a remplacer tout le contenu de canalu.py (dans ""addons\plugin.video.freplay\resources\lib\channels"") par celui qui est ici : 
https://raw.githubusercontent.com/spmjc/plugin.video.freplay/b544e2aaed8282bca025198399d50aea553348e0/resources/lib/channels/canalu.py

**Comment by orion2036** [comment]
J'ai suivi tes consignes JUL1EN094 :) Le problème d'encodage est résolu, les caractères XML n'apparaissent plus dans le volet de description des vidéos, sauf sur certaines descriptions qui se terminent par les caractères ]]> . La date de diffusion est 31/11/65535 pour toutes les vidéos. Le thème "Economie et Gestion" retourne une erreur, impossible d'accéder aux vidéos correspondantes.

**Comment by spmjc** [comment]
Plus d'erreur a l'ouverture de la rubrique eco-gestion
]]> n'aparaissent plus
Je laisse l'autre Julien augmenter le nb de videos.
Un exemple de rubrique ou le nb de video dans Kodi est pas le meme que sur le site pourrait aider..

**Comment by sy6sy2** [comment]
Nouveau fichier pour Canal U. 
Utilisation directe du site ; on ne passe plus par le RSS qui avait l'air trop limité.
A tester ...
c1a9a3efa4e00ce14247102d27789afa5114a9f4
