### ISSUE TITLE
Wat.tv

### ISSUE THREAD

**Issue by spmjc** [spmjc/plugin.video.freplay#48]
Authentication
POST https://www.wat.tv/v4/appmobile/user/authentication
password: xxx
username: xxx (login or email)

returns ts + token + userid

My Channels
POST https://www.wat.tv/v4/appmobile/user/subscriptions/channel
login: xxx
token: xxx
ts: xxx

returns list of channels

TF1 videos, cookies?

**Comment by inrepublica** [comment]
Juste pour signaler qu'avec le dernier commit il traîne ton mail et un mot de passe...

**Comment by spmjc** [comment]
Lol. Merci

**Comment by TmpName** [comment]
Salut, il n'y aurait pas une autre API plus complete autre que pour mobile par hazard ?
Je suis en train de comparer les resulats de l'addon et du site WEB de TF1, et il me manque pas mal de resulats, par exmple la serie 'Zoo' ou on peut trouver les replays des premiers episodes.
