### ISSUE TITLE
Tete a claques

### ISSUE THREAD

**Issue by spmjc** [spmjc/plugin.video.freplay#49]
Pages <span class="pageNums"><a href="http://m.tetesaclaques.tv/serietele/par_date/1" title="Page 1" class="pageNum">1</a> <a href="http://m.tetesaclaques.tv/serietele/par_date/2" title="Page 2" class="pageNum active">2</a> </span>

episodes

<div class="wrapCapsule flLeft">
            <a href="http://m.tetesaclaques.tv/le_maniaque_videpisode2871" title="Voir la vidéo" class="titreThumb">Le maniaque<br /><span class="saison-episode">Épisode 5</span></a>
            <img src="public/images/vignette/s01ep05_le_maniaque.jpg" width="300" height="127" alt="Le maniaque" class="thumb" border="0">
            <div class="votes">
            <img src="http://m.tetesaclaques.tv/public/images/starActive.png" width="16" height="14" alt="Étoile 1" class="star" border="0"><img src="http://m.tetesaclaques.tv/public/images/starActive.png" width="16" height="14" alt="Étoile 2" class="star" border="0"><img src="http://m.tetesaclaques.tv/public/images/starActive.png" width="16" height="14" alt="Étoile 3" class="star" border="0"><img src="http://m.tetesaclaques.tv/public/images/starActive.png" width="16" height="14" alt="Étoile 4" class="star" border="0"><img src="http://m.tetesaclaques.tv/public/images/starActive.png" width="16" height="14" alt="Étoile 5" class="star last" border="0">          <p class="nbVoteStar">5 113 votes</p></div>

```
        <div class="vues">372 599 vues</div>
    </div><!--/wrapCapsule -->
```

Videos link (JSON)
flowplayer("player", "public/js/flow-player/flowplayer.commercial-3.2.10.swf",{
                log: { level: 'debug', filter: 'org.flowplayer.captions.' },
                wmode: "opaque", // This allows the HTML to hide the flash content
                backgroundColor: '#000000',
                key: "#$6b2d0be7cb6d704909f",
                clip: {
                    captionUrl: soustitres,
                    scaling : 'fit',  
                    urlResolvers: 'brselect',
                    bitrates: [
                        { 
                            url: "http://216.46.7.230/content/s01e05_le_maniaque_qc_V_2_32OL.mp4",
                            width: 615, bitrate: 215, isDefault: true, hd:true
                        },
                        { 
                            url: "http://216.46.7.230/content/lorez/s01e05_le_maniaque_qc_V_2_32OL.mp4",
                            width: 615, bitrate: 165, sd: true 
                        }
                    ],
                    //provider: "",
                    //netConnectionUrl : "",
                    //bufferLength: "",
                    //autoBuffering: "",

```
                provider: 'lighttpd',
                autoBuffering: 'true',
                showCaptions: true,
                autoPlay: 'true'
            },
            play: {
                // label text at end of video clip
                opacity: 0.0,
                label: null,
                replayLabel: null 
            },
            plugins: pluginsConfig
        });
```

**Comment by gdusart** [comment]
Il y a un addon fonctionnel ici: http://media-passion.fr/addons/?Page=View&ID=plugin.video.tetesaclaques.tv

**Comment by gdusart** [comment]
J'ai eu le temps d'y regarder, voir  https://github.com/spmjc/plugin.video.freplay/pull/108
