### ISSUE TITLE
Institut national de l'audiovisuel www.ina.fr

### ISSUE THREAD

**Issue by orion2036** [spmjc/plugin.video.freplay#50]
Suite au lancement d'une offre a 2.99€/mois, le site risque d'etre saturé. C'est l'occasion pour des millions de français de retrouver des programmes tv de leur enfance, de leur jeunesse.

**Comment by orion2036** [comment]
Bonjour à tous, 
Merci pour cette superbe version 0.6.4
Je relance l'idée d'intégrer le site de l'Ina qui represente le patrimoine télévisuel français www.ina.fr (si c'est techniquement possible)
Bonne continuation.

Hello everybody,
Thank you for this nice 0.6.4  version.
I renew the idea of the integration of www.ina.fr that is the memory of the french tv (if it is technically possible)
Successfull continuation.

**Comment by gdusart** [comment]
Je suis en train d'y travailler

**Comment by orion2036** [comment]
Merci :)

**Comment by gdusart** [comment]
Voir pull request #73

**Comment by orion2036** [comment]
Superbe ajout à Freplay, je viens de tester l’accès aux vidéos de l'INA, tout semble ok, encore merci gdusart . C'est magique de revoir ces vieilles emissions aussi simplement grâce à Kodi et Freplay :)

**Comment by gdusart** [comment]
Avec plaisir, je regarderai si je peux ajouter la prise en charge des catégories populaires car le chargement de la liste complète des émissions est un peu long à mon goût (mais avec le cache ça va)
