### ISSUE TITLE
Random error on pluzz2

### ISSUE THREAD

**Issue by TmpName** [spmjc/plugin.video.freplay#56]
I have some random error 404 on this source since 1/2 months, but I have them all the time since 2 days, I have corrected them with adding a user agent at http request.

pluzz2.py line 58

> > ```
> >  url9 = showInfo % (emission['id_diffusion'])
> >   print url9
> >   headers = { 'User-Agent' : 'Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36' }
> >   req = urllib2.Request(url9,None,headers)
> >   content = urllib2.urlopen(req)
> >   filPrgm = content.read()
> >   #filPrgm        = urllib2.urlopen(url9).read()
> > ```

It's a debug code ^^, you can clean it.

**Comment by spmjc** [comment]
C'est ce que j'ai fait dans la nouvelle version. Mais ce ne suffit pas
nécessairement..
C'est étrange comme erreur.
En fait le lien fonctionne, une fois que tu las l as ouvert sur
ordinateur...

**Comment by JUL1EN094** [comment]
Cc,
La nouvelle version de SPM à l'air de fonctionner chez moi sans ouverture par Chrome au préalable. A vérifier de votre côté. 
Si cela ne fonctionne pas bien, on pourrais regarder du côté du module requests (en mode session) pour les appels web.

**Comment by TmpName** [comment]
La, c'est un peu mort pour tester, vu que j'ai été voir directement le site via navigateur pour mes tests, mais la ce soir ca marche encore juste avec le user-agent.
Des que cela redeconne je vous tiens au courant.
