### ISSUE TITLE
BeCurious TV

### ISSUE THREAD

**Issue by spmjc** [spmjc/plugin.video.freplay#58]
Categories and Shows
http://becurioustv.com/fr/shows

**Comment by sy6sy2** [comment]
Je veux bien essayer de me charger de cette chaine. Est ce que je continue avec des pull request ou est ce que tu peux m'ajouter au repo pour que je puisse pusher directement ?

Merci de ta réponse.

Sylvain

**Comment by spmjc** [comment]
il y a l'air d'y avoir plus de contenu ici (et plus interessant)
http://zonevideo.telequebec.tv/
Mais tu commences par ce que tu preferes.

**Comment by spmjc** [comment]
Sylvain, contacte moi en MP depuis le forum media passion STP
(Je n'ai pas vu d'option similaire sur gitub)

**Comment by sy6sy2** [comment]
Normalement BecuriousTV est maintenant fonctionnel. Je ferrai surement quelques améliorations un peu plus tard.
