### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by romain74** [spmjc/plugin.video.freplay#59]
I've been using it for a while on raspberry with XBMC. Since a couple of week it's not working at all anymore. As soon as I try to launch a replay I get the error please consult log for error. Any idea ?

Cheers

Romain

**Comment by sy6sy2** [comment]
Hello Romain,
On which channel have you an error ? All ?

Sylvain

**Comment by spmjc** [comment]
Did you install from the repo?
Can you send your log?

**Comment by JUL1EN094** [comment]
Pas de réponse depuis le 24mars. Je clos
