### ISSUE TITLE
Tou.tv probleme

### ISSUE THREAD

**Issue by TmpName** [spmjc/plugin.video.freplay#63]
En ce moment aucune video ne se lance sur Tou.tv. enfin du moins chez moi.

**Comment by spmjc** [comment]
Ils ont mis a jour leur API
Donc, a corriger:
Liste programmes:
http://ici.tou.tv/presentation/section/rattrapage?v=2&d=ipad&includePartnerTeaser=false
(ajouter configuration "IsFree": true)
Lien video
http://api.radio-canada.ca/ValidationMedia/v1/Validation.html?appCode=toutv&idMedia=122445&deviceType=ipad&output=json

**Comment by TmpName** [comment]
Ok, bon ben je viens de tester plus attentivement, c'est mort pour moi, je viens de voir le prb.
{"url":null,"message":"Le contenu sÃ©lectionnÃ© n\u0027est pas disponible dans votre pays","errorCode":1,"params":null,"bitrates":null}

**Comment by spmjc** [comment]
Ah.. je m'attendais pas a ce que tu le developpes :)
Il y a un autre parametre si tu veux voir ailleurs qu'au Canada: "IsGeolocalized": false

**Comment by TmpName** [comment]
Lol, dsl, je tape d'abord, je valide et apres je relis.
Mais meme avec &IsGeolocalized=false j'ai le meme message, sans passer par des proxys je pense que je peux faire une croix sur ce site.

**Comment by spmjc** [comment]
Je n'ai pas de proxy la ou je suis et je n'avais pas de message d erreur
quand je récupérai le json.
Mais pas testé la vidéo..

**Comment by spmjc** [comment]
Ah non.. C'est pas dans url le paramètre isgeo... Ou paramètre isfree.
C'est dans le fichier JSON
Faut filtrer les vidéos qui ont les 2 pour toi

**Comment by TmpName** [comment]
En fait je teste ca.
http://pastebin.com/KsZvFP2B
Je recupere le premier json qui me donne l'id mais apres je n'ai plus le second.

**Comment by spmjc** [comment]
J'ai oublie 1 etape.. dsl
Ce qu'il faut faire:
1 Recueperer le json des programmes
2 Parser le fichier et recup json['url'](et description et...) de tous les energistrements qui ont 
json['IsFree']=true et json['IsGeolocalized']=false
3 Recuperer le json http://ici.tou.tv/presentation-json['url']?v=2&d=ipad&includePartnerTeaser=false
4 Recup json['IdMedia']
5 Recuperer le json http://api.radio-canada.ca/ValidationMedia/v1/Validation.html?appCode=toutv&idMedia=json['IdMedia']&deviceType=ipad&output=json

**Comment by TmpName** [comment]
Effectivement ca marche, mais du coup, le nbre de video prend une claque ^^.
Tu vas faire comment, activer/desactiver la gelocalisation via les options ? Car je pense qu'il y a des heureux venards qui habitent au canada.

**Comment by spmjc** [comment]
Oui ou alors je teste si utilisateur a acces a une des videos geobloquees... si il a acces, on affiche, sinon on masque..

Effectivement, ca reduit les possibilites, mais la liste affichee est aussi plus realiste, vu qu'avant la moitie ne marchait pas. J'habite aux US et utilise un DNS pour bypass la geolocalisation, mais les videos payantes me bloquaient souvent.

**Comment by TmpName** [comment]
Je pense que le test sera mieux, car perso les options je ne vais les voir que si j'ai un probleme, ou si je veux voir si je peux trouver une amelioration. L'user lamda ne se prend jamais la tete.
Sinon masquee par defaut, a activer, mais je connais pas la taille de la communaute canadienne sur cet addon, se serait dommage.
