### ISSUE TITLE
Add M6

### ISSUE THREAD

**Issue by spmjc** [spmjc/plugin.video.freplay#7]
Info to retrieve channels to be added here:

Test urls with https://github.com/Shani-08/ShaniXBMCWork/tree/master/zips/plugin.video.f4mTester

http://fr-m6.videoplaza.tv/proxy/distributor/v2?rt=vast_2.0&st=0%3A0%2C3%2C4%2C10%2C20%3A1%2C32%2C33%2C34%2C35%2C36%2C37%2C91&pf=ad_21&cv=1.0.13.3.0-ea&m=LG-D855&t=pack_rg%2Cpack_femmes%2Cpack_art_de_vivre%2Cpack_25_49%2Cpack_maman%2Cles-reines-du-shopping%2Ccatchup%2Clongform%2Cherve_hubert_production%2Cstyles&s=styles%2Fles-reines-du-shopping&cf=long_form&tt=p&dcid=android_phone&pid=fe6e8429-e91d-4166-9dcf-7181e9124b4c&rnd=464d8f4d-fe4e-489f-ab1d-eb4e7540a22d

**Comment by sy6sy2** [comment]
Codage du replay du groupe M6 en cours

**Comment by sy6sy2** [comment]
Fait !

**Comment by spmjc** [comment]
Toutes les vidéos m6 fonctionnent vraiment??

**Comment by sy6sy2** [comment]
La très grande majorité oui, en cherchant au hasard je suis tombé sur NCIS qui n’a pas fonctionné (je suis en train de regarder). Mais les grandes émissions de divertissements (L’amour est dans le pré, le meilleur pâtissier, la france cherche un incroyable talent) fonctionne.

**Comment by sy6sy2** [comment]
Je me demande si il ne faut pas s’authentifier pour ces quelques videos qui ne fonctionnent pas. Je vais regarder ça de plus près.

**Comment by spmjc** [comment]
Et ben bravo. Ça va rendre beaucoup de monde heureux!!
Est ce qu'il est possible de déterminer quelles émissions ne fonctionneront
pas où il faut faire lecture pour s'en rendre compte?

**Comment by sy6sy2** [comment]
Tant mieux alors, et je fais partie des premiers heureux :-P

Pour l’instant on s’en rend compte en voulant lancer la vidéo, mais dans le JSON il a peut être un flag qui change par rapport aux autres vidéos …
