### ISSUE TITLE
Replay M6 : quelques videos ne fonctionnent pas

### ISSUE THREAD

**Issue by sy6sy2** [spmjc/plugin.video.freplay#75]
Pour M6 quelques videos ne fonctionnent pas (Par exemple NCSI), on a pourtant le lien m3u8 ...
Peut être qu'il faut s'authentifier comme sur le site 6play. 

Recherche en cours

**Comment by sy6sy2** [comment]
Ces mêmes vidéos ne fonctionnent pas sur Captytv non plus.

Fonctionne sur desktop connecté sur le site 6play
Sur iPhone Safari ne fonctionne pas "Pour des raisons de droits cette vidéo n'est accessible que sur l'application 6play"

Pistes :
- User-agent
- Headers
- Authentication

**Comment by spmjc** [comment]
Je pense que ce sont les DRM qui restent.

**Comment by sy6sy2** [comment]
Notification d'erreur en cas de vidéo protégée par DRM
