### ISSUE TITLE
Erreur "No module named _multiprocessing"

### ISSUE THREAD

**Issue by jeff2900** [spmjc/plugin.video.freplay#77]
Bonjour,
Je vous remercie pour votre travail. Votre plugin est très pratique pour regarder la TV de rattrapage avec kodi.

Il me manquait les chaines 6play et lorsque j'ai vu qu'elle avait été ajouter ici je me suis empresse de récupérer les scripts.
Mais malheureusement j'ai un message d'erreur au chargement du plugin.

J'utilise kodi 16.1 et spmc 16.4.2 avec des boitiers android 5.1 et0 6.0 et tous les deux ont le même message d'erreur.
J'ai également teste le plugin sous windows 10 et là il fonctionne correctement.
Pour contourner le problème, j'ai remplacé le script ina.py par un placébo.

Voici le message d'erreur de spmc sous android:
20:56:12 T:18446744073087486256   DEBUG: Addon=FReplay 0.6.4
20:56:12 T:18446744073087486256   DEBUG: Addon Path=/storage/emulated/0/Android/data/com.semperpax.spmctest/files/.spmc/addons/plugin.video.freplay
20:56:12 T:18446744073087486256   DEBUG: {}
20:56:13 T:18446744073087486256   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named _multiprocessing
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmctest/files/.spmc/addons/plugin.video.freplay/default.py", line 62, in <module>
                                                utils.init()
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmctest/files/.spmc/addons/plugin.video.freplay/resources/lib/utils.py", line 28, in init
                                                channelModule = imp.load_module(file[:-3], f, filename, description)
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmctest/files/.spmc/addons/plugin.video.freplay/resources/lib/channels/ina.py", line 6, in <module>
                                                from multiprocessing.dummy import Pool as ThreadPool
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.6/multiprocessing/__init__.py", line 83, in <module>
                                            ImportError: No module named _multiprocessing
                                            -->End of Python script error report<--
20:56:13 T:18446744073430628656   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
20:56:13 T:18446744073430628656   DEBUG: Window DialogKaiToast.xml was already loaded
20:56:13 T:18446744073430628656   DEBUG: Alloc resources: 0.00ms
20:56:13 T:18446744073087486256    INFO: Python script stopped
20:56:13 T:18446744073087486256   DEBUG: Thread LanguageInvoker 18446744073087486256 terminating
20:56:13 T:18446744073430628656   DEBUG:  WaitOnScriptResult - plugin exited prematurely - terminating
20:56:13 T:18446744073430628656   ERROR: GetDirectory - Error getting plugin://plugin.video.freplay/
20:56:13 T:18446744073430628656   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.freplay/) failed
20:56:13 T:18446744073430628656   DEBUG: CGUIMediaWindow::GetDirectory ()
20:56:13 T:18446744073430628656   DEBUG:   ParentPath = [plugin://plugin.video.freplay/]
20:56:13 T:18446744073087486256   DEBUG: Thread BackgroundLoader start, auto delete: false

En vous remercie pour votre travail.
Cordialement,

**Comment by gdusart** [comment]
Bonjour,

J'ai en effet utilisé le module multiprocessing pour le scrapper ina. Faudrait-il ajouter une dépendance vers ce module dans le script ?

**Comment by jeff2900** [comment]
Bonjour,

Merci pour votre réponse rapide.

Le but de mon message était uniquement de reporter l'erreur python. Comme je l'indique. J'ai supprimé la chaine INA du plugin pour pouvoir l'utiliser sous android.

S'il n'est pas possible d'éviter l'usage du module python 'multiprocessing' dans le script ina.py, comme je ne peux pas recompiler les packages kodi et spmc pour android, il serait bien d'avoir une solution pour éviter cette erreur.
- Soit ajouter la librairie 'multiprocessing' au plugin.
- Soit faire un test d'environnement pour ignorer l'erreur python sous android.

Je vous laisse voir ce qui est le plus simple à réaliser.

Cordialement,

**Comment by TmpName** [comment]
Salut.
C'est quoi l'utilite de ce module stp ? Je ne le connaissais meme pas.

**Comment by gdusart** [comment]
Salut,

ca me permet de lancer plusieurs threads qui vont parser les chaines en parallèle puis d’agréger les résultats. Comme il y a beaucoup de catégories sur INA, ça accélère nettement  le chargement.

J'ai testé sur plusieurs instances linux ici et ça fonctionne bien car le plugin est installé dans mon runtime python.

Je ne suis pas très familier avec les plugins kodi donc je ne sais pas s'il possible de forcer l'installation de modules manquants ?

**Comment by gdusart** [comment]
Il semble que ce ne soit pas supporté sur Android...
http://forum.kodi.tv/showthread.php?tid=139225

**Comment by jeff2900** [comment]
Bonjour,

Je vous propose le correctif suivant dans ina.py pour pouvoir utiliser le plugin freplay.
` ina.py:

```
try:
  from multiprocessing.dummy import Pool as ThreadPool
except:
  print("Error ThreadPool")
```

`
Ainsi le plugin fonctionne sous Android et Windows. 
La chaine INA fonctionne sous Windows 10 mais elle est en erreur sous Android sans bloquer le plgin.

Cordialement,

**Comment by JUL1EN094** [comment]
Bonjour,

Pour moi le mieux est d'utiliser threading.thread plutôt que multiprocessing (qui ne s'implémente pas parfaitement sur toutes les plateformes). Je vais essayer de trouver le temps de modifier le code et je vous envoie ca

a+

**Comment by gdusart** [comment]
Merci Julien, je pense que c'est la meilleure solution. Je voulais le faire mais je suis un peu limite niveau temps cette semaine.

**Comment by JUL1EN094** [comment]
Re,

Première tentative d'implémentation sur le dernier commit que j'ai fait : https://github.com/spmjc/plugin.video.freplay/commit/ce4446ae328d42e4783893888718ed4c6cd65f75

De plus j'ai modifié des nom de variables (certaines déclarées dans des fonctions portent le même nom que des variables globales.... ca peut  perturber). Exemple : channel, img,title.. 

Il reste un point a coder pour le thread : attendre qu'ils soient tous finis avant faire le return (là des fois il affiche la liste alors que ttes les lettres n'ont pas finis de télécharger).

 A votre dispo pour échanger

**Comment by gdusart** [comment]
Merci !

Voir #79

**Comment by JUL1EN094** [comment]
Nickel. On peut clore l'issue je pense ?

**Comment by jeff2900** [comment]
Bonjour,

@JUL1EN094, merci beaucoup pour votre contribution.
Je viens de tester le script ina.py sous android uniquement. Il fonctionne correctement et est même très rapide.
Aussi permettez-moi une petite remarque. Serait-il possible de créer des sous catégories/thèmes comme sur le site ina ?
Car pour l'instant il y a 424 suggestion classées par ordre alphabétique et il n'est pas aisé de s'y retrouver.

Cordialement.
