### ISSUE TITLE
Support appli mobile 6play

### ISSUE THREAD

**Issue by tempo22** [spmjc/plugin.video.freplay#80]
Bonjour,

j'aimerai bien apporter le support de l'appli mobile 6play sur Kodi.
J'utilise l'appli Yatse pour controler Kodi et Yatse ajoute "Jouer sur Kodi" dans les options de partage.

Lorsque je partage une video de l'appli 6play vers Kodi, il y a une réaction mais aucune appli ne se lance. Est-ce possible de faire en sorte que l'appli freplay ce lance quand on recoit une url 6play ?

Je pense que l'url recue est dans ce format :

`urlVideo = 'http://www.6play.fr/%s-p_%s/%s-c_%s'
            #  program;code  program;id.   episode;code.   episode;id`

Mais je ne sais quoi modifier dans le code pour la prise en compte automatique par kodi.

**Comment by sy6sy2** [comment]
Bonjour ! 

Super intéressant comme idée, personnellement je n'ai pas d'Android donc je passe la main mais si j'arrive à récupérer un Android pourquoi pas regarder à ça !

Bon courage à ceux qui vont s'y pencher ;-)

**Comment by tempo22** [comment]
L'add-on youtube utilise URLResolver, je pense qu'il faut chercher de ce coté
