### ISSUE TITLE
Allociné erreurs et catégories vides

### ISSUE THREAD

**Issue by sy6sy2** [spmjc/plugin.video.freplay#81]
Problème remonté par NenesSix sur http://media-passion.fr/add-ons-video/freplay-french-replay/320/

**Comment by sy6sy2** [comment]
Je vais m'y pencher et par la meme occasion voir si on ne peut pas ajouter plus de contenu !

**Comment by sy6sy2** [comment]
Début réécriture de la chaine allociné --> allociné2.py

**Comment by sy6sy2** [comment]
Réécriture de la chaine allociné pour l'instant en plusieurs morceaux (Cinéma, émissions et séries)
Cinéma et émissions en "beta"
Séries en cours d'écriture

**Comment by spmjc** [comment]
La maj fonctionne pour moi
