### ISSUE TITLE
supporter Auvio ? (télévision belge)

### ISSUE THREAD

**Issue by gordielachance** [spmjc/plugin.video.freplay#88]
Salut !
Super plugin !!! 
J'aime particulièrement la possibilité d'ajouter des favoris par émission.

J'aurais voulu savoir si vous seriez d'accord d'ajouter [Auvio](http://www.rtbf.be/auvio/) (chaînes belges francophones) à votre plugin.
Il y a déjà un [plugin existant ici](https://github.com/rickybiscus/plugin.video.auvio); ce serait encore mieux si c'était intégré au vôtre !

Merci !

**Comment by sy6sy2** [comment]
Bonjour gordielachance !

Merci de ton retour ;-)

J'ajoute le label "Channel Request" à ton issue, moi ou un autre dev essaierons de trouver le temps d'y jeter un oeil ;-)

On tiendra informé de l'avancement sur cette issue !

Bonne journée !

**Comment by sy6sy2** [comment]
Je me lance dans Auvio, ça n'a pas l'air trop compliqué.

Par contre n'étant pas en Belgique actuellement il faudra que tu testes le bon fonctionnement des vidéos gordielachance.
Sinon je passe en Belgique mi Janvier, je pourrai tester

**Comment by gordielachance** [comment]
Pas de soucis, je peux tester !

Merci beaucoup !!

G.

Le 27 décembre 2016 à 11:45, Sylvain CECCHETTO <notifications@github.com> a
écrit :

**Comment by sy6sy2** [comment]
Voici le premier commit pour la chaine : 8a5c32983f1d127a9ce4d7b0e7d61e55f7c0b843

Il faut encore que j'ajoute les infos sur chaque media mais je te laisse déjà tester ça ;-)

**Comment by gordielachance** [comment]
Voilà, j'ai testé (sur la dernière release officielle pour windows).
On dirait que certaines catégories fonctionnent et pas d'autres.

Par exemple, sur une sélection aléatoire, j'arrive à voir

   - documentaire > les carnets du bourlingueur
   - culture > libre échange
   - vie quotidienne > matière grise express

mais pas

   - info > JT 19h30
   - humour > tout le monde veut prendre sa place
   - culture > hep taxi ! (peut être un rapport avec le point d'exclamation
   ?)
   - documentaire > la vie secrète de nos enfants
   - vie quotidienne > les jardins de rêve de Luc Noël
   - vie quotidienne > on n'est pas des pigeons

Il n'indique pas d'erreur, mais le loader ne s'arrête pas de tourner à
moins que j'appuie sur ESC.

Je comprend pas trop ce qui peut amener ça, on dirait que c'est un peu
aléatoire... ?

G

2016-12-27 15:25 GMT+01:00 Sylvain CECCHETTO <notifications@github.com>:

**Comment by spmjc** [comment]
J'ai fait quelques tests.
Ca marche ici a part pour les videos geo localisees

Je ferme pour instant
