### ISSUE TITLE
Les vidéos ne se lancent pas

### ISSUE THREAD

**Issue by JulienBesp** [spmjc/plugin.video.freplay#89]
Bonjour, est-il obligatoire d'être en France pour lire les videos? J'habite Dubai et je reçois pratiquement pour chaque vidéo un message d'erreur "Échec de la lecture d'un ou plusieurs fichiers. Consulter le journal pour plus d'informations sur ce message."

Principalement sur C8 aucune vidéos ne marchent...
Que dois-je faire?

Merci pour votre aide
Cordialement

**Comment by spmjc** [comment]
Oui, il faut theoriquement etre en france.
Mais je suis au USA et ca marche tres bien grace a unotelly:
https://www2.unotelly.com/
