### ISSUE TITLE
TF1 - 404 Error for Series

### ISSUE THREAD

**Issue by melonboy666** [spmjc/plugin.video.freplay#91]
Thanks for all your hard work! You make my wife very happy which makes my life easier! Sorry to write in English, my written French is terrible!

Trying to launch a new series from TF1 (24 HEURES EN QUESTIONS) and getting the 404 error. Do you think there is a way to fix? 

I confirm that this is correct:

**http%3a%2f%2fwww.lci.fr%2femission%2f18h-20h-24-heures-en-questions%2f**

Thanks again. Awesome job.
[TF1.txt](https://github.com/spmjc/plugin.video.freplay/files/721271/TF1.txt)

**Comment by ahivert** [comment]
Have you tried to update to the latest version 0.6.8 ?
