### ISSUE TITLE
Plus de chaines Documentaires

### ISSUE THREAD

**Issue by sabtri03** [spmjc/plugin.video.freplay#92]
En premier, je regarde reguliérement Freplay  et merci beaucoup !
Et j'aimerais bien avoir accès a plus de documentaire tel que Planet+ (http://www.planeteplus.com/), Science&Vie (http://www.science-et-vie.tv/live-replay.aspx), DiscoveryChannel (http://www.discoverychannel.fr/videos/) ou National Geographic (http://www.natgeotv.com/fr/videos).
Si possible bien sur !
Merci ,

**Comment by spmjc** [comment]
Je lis ca tard, mais bonne idee, je regarde

**Comment by sabtri03** [comment]
Merci pas de problème ! Vaut mieux tard que jamais meme su ca n est pas du tout une  priorité !

**Comment by spmjc** [comment]
J'ai travaille sur Nat Geo, mais ce sont des videos super courtes!

**Comment by sabtri03** [comment]
Oh Merci beaucoup ! C'est deja un bon debut.

**Comment by spmjc** [comment]
J'ai ajoute http://www.les-docus.com/.
Ca devrait te faire plaisir

**Comment by sabtri03** [comment]
Oh que ouii! C'est bien mieux que les autres chaines. Merci beaucoup !!!!

**Comment by spmjc** [comment]
Je ferme pour instant car les autres ont besoin d'un login
