### ISSUE TITLE
FReplay / Issue

### ISSUE THREAD

**Issue by wwark** [spmjc/plugin.video.freplay#96]
Bonjour,

J'ai FReplay installé dans un KODI 17 sur Android et sur une Debian (Testing).

Sur l'android, j'ai bien toutes les chaines qui sont listées alors que sur la debian (Testing) j'ai ces comportements 
* toutes les chaines Pluzz (France2, 3, 4 et 5), BFMTV, .... sont en doubles
* TF1, HD1, RTBF, Allociné,.... ne s'affichent pas.
J'ai déjà supprimé tout mon répertoire ".kodi" avec tous settings de kodi mais le problème persiste.

Est-ce quelqu'un a déjà eu ce comportement ?

D'avance merci,
Wark.

**Comment by wwark** [comment]
Bonjour, 

La mise à jour de libBeautifulSoup4 a permi de régler de ce problème.

Merci,
Marc.

**Comment by spmjc** [comment]
Désolé de pas avoir résolu ça
