### ISSUE TITLE
Erreur vidéos TF1

### ISSUE THREAD

**Issue by denismerigoux** [spmjc/plugin.video.freplay#99]
Bonjour,

Merci pour ce plugin qui marche du tonnerre! Néanmoins depuis ce week-end impossible de récupérer les émissions de TF1... J'ai téléchargé la dernière version (0.6.7), voici le message d'erreur:
```
21:03:09.531 T:1421865968   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python 
callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'getText'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.freplay/default.py", line 149, in <module>
                                                globalvar.channels[channel][1].list_videos(channel, param))
                                              File "/home/osmc/.kodi/addons/plugin.video.freplay/resources/lib/channels/tf13.py", line 78, in list_videos
                                                videoType = videoType.getText().encode('utf-8').lower()
                                            AttributeError: 'NoneType' object has no attribute 'getText'
                                            -->End of Python script error report<--
21:03:09.633 T:1918890992  NOTICE: CAESinkPi:AddPackets Underrun (delay:0.00 frames:2205)
21:03:09.697 T:1958896560   ERROR: GetDirectory - Error getting plugin://plugin.video.freplay/?channel=tf1&mode=shows&name=Quotidien%20avec%20Yann%20Barth%c3%a8s&param=%2ftmc%2fquotidien-avec-yann-barthes
21:03:09.698 T:1958896560   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.freplay/?channel=tf1&mode=shows&name=Quotidien%20avec%20Yann%20Barth%c3%a8s&param=%2ftmc%2fquotidien-avec-yann-barthes) failed
```

TF1 a du changer quelque chose sur son API...

**Comment by dr1ss** [comment]
Je confirme

**Comment by rick60** [comment]
bonjour,

je confirme egalement 



j'aimerai bien aidé, mais j'ai aucune piste pour commencer à débugger et exécuter cette extension python
```
10:04:24 11265.552734 T:1457517472   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'getText'
                                            Traceback (most recent call last):
						File "/storage/.kodi/addons/plugin.video.freplay-0.6.7/default.py", line 149, in <module>
                                                globalvar.channels[channel][1].list_videos(channel, param))
                                              File "/storage/.kodi/addons/plugin.video.freplay-0.6.7/resources/lib/channels/tf13.py", line 78, in list_videos
                                                videoType = videoType.getText().encode('utf-8').lower()
                                            AttributeError: 'NoneType' object has no attribute 'getText'
                                            -->End of Python script error report<--
10:04:24 11265.565430 T:1963032576   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
```

**Comment by LHDN** [comment]
De mon côté, sur le replay web, c'est la première fois qu'on me demande de m'authentifier pour accéder à une vidéo. Changement de stratégie de TF1, il faut maintenant être authentifié ?

**Comment by LHDN** [comment]
Plus général d'ailleurs, les vidéos via le replay web en devant être authentifié ne se lancent pas chez moi. On est à Nan/NaN dans la barre de progression.

**Comment by gordielachance** [comment]
Idem pour TMC (qui appartient à TF1) ?
Je suppose qu'il faudrait pouvoir s'authentifier via le plugin.

**Comment by spmjc** [comment]
Je regarderai ce sur si j'ai un peu de temps.

**Comment by tug912** [comment]
A priori le "problème concerne toutes les chaines du groupe TF1 (donc inclue toutes les chaines liées TMC, HD1, Histoire, UshuaïaTV).

Il faut à présent s'inscrire sur le site pour avoir accès aux replay. Rien de bien méchant, mais pour l'instant aucune possibilité de rentrer ses identifiants dans FReplay.
Reste à savoir si cela fonctionnera uniquement pour le Replay TF1 ou également pour les chaines liées.

Merci par avance aux contributeurs qui bossent sur le sujet !

**Comment by pchevallier** [comment]
Je viens de regarder. En dépit de cette nouvelle 'restriction' d'imposer une identification pour des raisons commerciales et publicitaires que l'on peut comprendre, le code HTML a lui aussi été changé sur plusieurs endroits ce qui cause les problèmes que nous observons avec le plugin. 
Ce sont deux problèmes indépendants l'un de l'autre.

**Comment by pchevallier** [comment]
J'ai une nouvelle version freplay prête a être testé par ceux qui seraient intéressés et qui savent faire une installation 'manuelle' d'un addon en format 'zip'. 
Tout marche bien, au moins sur TF1, je n'ai pas testé les autres chaines (NT1, HT1, TMC, XTRA)

**Comment by blacksnacke** [comment]
@pchevallier je suis pret a le tester. Ou telecharger le fichier zip?

**Comment by spmjc** [comment]
Je pense a re-activer la version API.
Je ne savais meme pas qu'on eteait passer au parsing du site. :)
Les API seront quand meme plus stables, par definition.

Je vais regarder ca ce weekend

**Comment by spmjc** [comment]
Corrige dans 0.6.8
Utilisation des API au lieu du site Web

**Comment by rick60** [comment]
je test

**Comment by rick60** [comment]
je teste ca fonctionne

parfait

manque juste les thumbnails des aperçus

merci !!!!

**Comment by tug912** [comment]
Super, merci !
Pour l'install je l'ai fait manuellement, est ce qu'il y a un nouveau repo, ou un repo unique pour que les maj se fassent automatiquement à l'avenir ?
Je n'ai que le Repo de JUL1EN094 pour l'instant (mais la dernière version n'est pas pluggé)

Dans tous les cas merci pour le boulot !!!

**Comment by pchevallier** [comment]
Wow, bravo.  Désolé pour le retard dans ma réponse au fichier zip a tester (décalage horaire oblige), mais c'est mieux ainsi visiblement.  
Je m'étais attardé sur la version web car cela semblait être la cause du problème, ne réalisant pas que la version API similaire aux autres chaines était en attente dans un autre fichier pour être mise en production. 
@spmjc; veux-tu intégrer ces changements dans la branche 'masters' au cas où on perdait accès a l'API?
